name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.1
      - name: Set up JDK 25
        uses: actions/setup-java@v5.1.0
        with:
          distribution: 'oracle'
          java-version: '25'
          cache: 'maven'
      - name: task01
        id: task01
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: task01
          setup-command: ''
          command: mvn -Dtest=TestAssignment#task01 test
          timeout: 10
          max-score: 10
      - name: task02
        id: task02
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: task02
          setup-command: ''
          command: mvn -Dtest=TestAssignment#task02 test
          timeout: 10
          max-score: 10
      - name: task03
        id: task03
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: task03
          setup-command: ''
          command: mvn -Dtest=TestAssignment#task03 test
          timeout: 10
          max-score: 10
      - name: task04
        id: task04
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: task04
          setup-command: ''
          command: mvn -Dtest=TestAssignment#task04 test
          timeout: 10
          max-score: 10
      - name: task05
        id: task05
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: task05
          setup-command: ''
          command: mvn -Dtest=TestAssignment#task05 test
          timeout: 10
          max-score: 10
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TASK01_RESULTS: "${{steps.task01.outputs.result}}"
          TASK02_RESULTS: "${{steps.task02.outputs.result}}"
          TASK03_RESULTS: "${{steps.task03.outputs.result}}"
          TASK04_RESULTS: "${{steps.task04.outputs.result}}"
          TASK05_RESULTS: "${{steps.task05.outputs.result}}"
        with:
          runners: task01,task02,task03